### ISSUE TITLE
Auto-update broken: Updating 0.9.6 to 0.9.7 fails

### ISSUE THREAD

**Issue by nlmarco** [cloudstore/cloudstore#50]
java.io.IOException: entry 'backup/co.codewizards.cloudstore.server-0.9.6.backup-ipzjduva.tar.gz' closed at '65814528' before the '65818758' bytes specified in the header were written
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.closeArchiveEntry(TarArchiveOutputStream.java:348) ~[commons-compress-1.7.jar:1.7]
        at co.codewizards.cloudstore.updater.TarGzFile.writeTar(TarGzFile.java:110) [co.codewizards.cloudstore.updater-0.9.6.jar:na]
        at co.codewizards.cloudstore.updater.TarGzFile.writeTar(TarGzFile.java:114) [co.codewizards.cloudstore.updater-0.9.6.jar:na]
        at co.codewizards.cloudstore.updater.TarGzFile.compress(TarGzFile.java:73) [co.codewizards.cloudstore.updater-0.9.6.jar:na]
        at co.codewizards.cloudstore.updater.CloudStoreUpdater.run(CloudStoreUpdater.java:137) [co.codewizards.cloudstore.updater-0.9.6.jar:na]
        at co.codewizards.cloudstore.updater.CloudStoreUpdater.execute(CloudStoreUpdater.java:76) [co.codewizards.cloudstore.updater-0.9.6.jar:na]
        at co.codewizards.cloudstore.updater.CloudStoreUpdater.main(CloudStoreUpdater.java:48) [co.codewizards.cloudstore.updater-0.9.6.jar:na]

**Comment by nlmarco** [comment]
Unfortunately, this problem cannot be solved, because the old updater performs the update. A manual update is thus needed.

However, we must still fix this in order to make sure that the update from 0.9.7 onwards is going to be fully functional.

**Comment by nlmarco** [comment]
Hmmm... I think this bug was already fixed by me on 2015-10-06. The version 0.9.6 was released on 2015-04-07.

Hence: Sorry, everyone. You must perform a manual update. The version 0.9.7 should in the future be able to update itself correctly, again.

**Comment by nlmarco** [comment]
I added a JUnit test for CloudStoreUpdater to make sure, this error does not happen again.

**Comment by nlmarco** [comment]
**IMPORTANT: YOU MUST MANUALLY UPDATE!!!**

Because of this bug, we temporarily disabled the auto-update. But we're going to enable the auto-update on 2016-09-01 (or later, just as we find the time to work on CloudStore).

**If you do not manually upgrade your installation until then, you're going to face an endless loop!**
