### ISSUE TITLE
Disabling/removing an ignore-rule may cause error

### ISSUE THREAD

**Issue by nlmarco** [cloudstore/cloudstore#54]
java.lang.IllegalStateException: Just created directory, but corresponding RepoFile still does not exist after local sync: /home/mn/workspace/cloudstore.1/git/cloudstore/co.codewizards.cloudstore.test/target/repo/is46ijyt-nr9d8-local/1/dir1
	at co.codewizards.cloudstore.local.transport.FileRepoTransport.mkDir(FileRepoTransport.java:604)
	at co.codewizards.cloudstore.local.transport.FileRepoTransport.makeDirectory(FileRepoTransport.java:202)
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.makeDirectory(RepoToRepoSync.java:489)
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDirectory(RepoToRepoSync.java:474)
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:330)
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:237)
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:221)
	at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDown(RepoToRepoSync.java:167)
...

**Comment by nlmarco** [comment]
Fixed by taking the ignore-rules only into account when performing an initial local-repo-sync. The ignore-rules must not be considered, when the sync is already running, because the code invoking LocalRepoSync.sync(...) later on, expects it to create a RepoFile instance.

If the files are ignored during the initial local-repo-sync, they are not processed, later, anyway. The only situation when this can happen, is during adding or removal of an ignore-rule. And IMHO it is the correct procedure to ignore files only initially, i.e. during the sync-start. But if they're not ignored then, they must be processed the entire way through.
