### ISSUE TITLE
FileSystemException handling long non-Latin file names

### ISSUE THREAD

**Issue by nlmarco** [cloudstore/cloudstore#68]
Just encountered this exception saying that the file name was too long:

```
2017-07-20 04:34:15,310 [RepoSyncDaemonThread_0_0] ERROR c.c.c.c.r.s.RepoSyncDaemonImpl$WrapperRunnable - run: java.lang.RuntimeException: java.nio.file.FileSystemException: /media/calypso_sdb1/mn/ss/paruedee_publication/Publication/Sukhothai/ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี/.ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี.tex.subshare.properties: Der Dateiname ist zu lang
java.lang.RuntimeException: java.nio.file.FileSystemException: /media/calypso_sdb1/mn/ss/paruedee_publication/Publication/Sukhothai/ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี/.ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี.tex.subshare.properties: Der Dateiname ist zu lang
        at co.codewizards.cloudstore.core.oio.nio.NioFile.lastModified(NioFile.java:149) ~[co.codewizards.cloudstore.core.oio.nio-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.config.ConfigImpl.readIfNeeded(ConfigImpl.java:236) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.config.ConfigImpl.getPropertyAsNonEmptyTrimmedString(ConfigImpl.java:492) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.config.ConfigImpl.getPropertyAsEnum(ConfigImpl.java:562) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.config.ConfigImpl.getPropertyAsEnum(ConfigImpl.java:556) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.local.transport.FileRepoTransport.getFileWriteStrategy(FileRepoTransport.java:1032) ~[co.codewizards.cloudstore.local-0.10.0.jar:na]
        at co.codewizards.cloudstore.local.transport.FileRepoTransport.putFileData(FileRepoTransport.java:937) ~[co.codewizards.cloudstore.local-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.putFileData(RepoToRepoSync.java:710) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.putFileData(SsRepoToRepoSync.java:138) ~[org.subshare.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncFile(RepoToRepoSync.java:666) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:360) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:182) ~[org.subshare.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:256) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:171) ~[org.subshare.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:228) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDown(RepoToRepoSync.java:174) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:137) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) ~[co.codewizards.cloudstore.core-0.10.0.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.nio.file.FileSystemException: /media/calypso_sdb1/mn/ss/paruedee_publication/Publication/Sukhothai/ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี/.ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี.tex.subshare.properties: Der Dateiname ist zu lang
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[na:1.8.0_131]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_131]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_131]
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[na:1.8.0_131]
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[na:1.8.0_131]
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[na:1.8.0_131]
        at java.nio.file.Files.readAttributes(Files.java:1737) ~[na:1.8.0_131]
        at co.codewizards.cloudstore.core.oio.nio.NioFile.lastModified(NioFile.java:143) ~[co.codewizards.cloudstore.core.oio.nio-0.10.0.jar:na]
        ... 24 common frames omitted
```

**Comment by nlmarco** [comment]
Note: This file does *not* exist. The error occurs while accessing lastModified().

**Comment by nlmarco** [comment]
Fixed:

Removed NioFile.lastModified() (i.e. falling back to java.io.File.lastModified()). Also changed NioFile.getLastModifiedNoFollow() to behave the same and return 0, if the file does not exist.

**Comment by nlmarco** [comment]
For reference:

https://serverfault.com/questions/9546/filename-length-limits-on-linux
https://serverfault.com/questions/542450/is-the-ext3-filename-limited-to-255-symbols-or-255-bytes

The Ext3 file system has a limit of 255 bytes (not chars!) per file name. Thus, using UTF-8 for non-latin file names causes the the actual file name length in characters to be much shorter -- depending on the characters. It might be as little as 63 characters only!

**Comment by nlmarco** [comment]
Next exception:

```
2017-07-20 05:39:19,947 [RepoSyncDaemonThread_0_8] ERROR c.c.c.c.r.s.RepoSyncDaemonImpl$WrapperRunnable - run: java.lang.RuntimeException: Writing file '/media/calypso_sdb1/mn/ss/paruedee_publication/Publication/Sukhothai/ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี/.subshare-tmp/chunk_ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี.tex_0.xml' failed: java.io.FileNotFoundException: /media/calypso_sdb1/mn/ss/paruedee_publication/Publication/Sukhothai/ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี/.subshare-tmp/chunk_ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี.tex_0.xml (Der Dateiname ist zu lang)
java.lang.RuntimeException: Writing file '/media/calypso_sdb1/mn/ss/paruedee_publication/Publication/Sukhothai/ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี/.subshare-tmp/chunk_ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี.tex_0.xml' failed: java.io.FileNotFoundException: /media/calypso_sdb1/mn/ss/paruedee_publication/Publication/Sukhothai/ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี/.subshare-tmp/chunk_ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี.tex_0.xml (Der Dateiname ist zu lang)
        at co.codewizards.cloudstore.core.dto.jaxb.DtoIo.serialize(DtoIo.java:91) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.local.transport.TempChunkFileManager.writeFileDataToTempChunkFile(TempChunkFileManager.java:63) ~[co.codewizards.cloudstore.local-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.local.transport.FileRepoTransport.putFileData(FileRepoTransport.java:945) ~[co.codewizards.cloudstore.local-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.putFileData(RepoToRepoSync.java:710) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.putFileData(SsRepoToRepoSync.java:138) ~[org.subshare.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncFile(RepoToRepoSync.java:666) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:360) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:182) ~[org.subshare.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:256) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:171) ~[org.subshare.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:228) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDown(RepoToRepoSync.java:174) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:137) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at org.subshare.core.repo.sync.SsRepoToRepoSync.sync(SsRepoToRepoSync.java:65) ~[org.subshare.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncRunner.run(RepoSyncRunner.java:51) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoSyncDaemonImpl$WrapperRunnable.run(RepoSyncDaemonImpl.java:123) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.io.FileNotFoundException: /media/calypso_sdb1/mn/ss/paruedee_publication/Publication/Sukhothai/ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี/.subshare-tmp/chunk_ปัญหาหมอกควันกับภูมิทัศน์ที่เปลี่ยนไปในภูมิภาคเอเชียตะวันออกและเอเชียตะวันออกเฉี.tex_0.xml (Der Dateiname ist zu lang)
        at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_131]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_131]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_131]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_131]
        at co.codewizards.cloudstore.core.oio.IoFile.createOutputStream(IoFile.java:262) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        at co.codewizards.cloudstore.core.dto.jaxb.DtoIo.serialize(DtoIo.java:87) ~[co.codewizards.cloudstore.core-0.10.1-SNAPSHOT.jar:na]
        ... 20 common frames omitted
```

**Comment by nlmarco** [comment]
Changed fix in NioFile.lastModified() again, because the behaviour of the new nio-API and the old java.io.File-API is *not* the same -- thus breaking tests :-(

**Comment by nlmarco** [comment]
Fixed the 2nd exception by switching from full file.name to hash(file.name) in order to guarantee that the name never becomes too long (after adding prefix and suffix).

**Comment by nlmarco** [comment]
Seems fine now. Tests are successful again and subshare completed my productive sync without any hassle. The subshare tests are still running, but I don't expect any problem, there => closing.
