### ISSUE TITLE
URISyntaxException with localRoot = /

### ISSUE THREAD

**Issue by nlmarco** [cloudstore/cloudstore#72]
I want to synchronize / (with quite a few ignore-rules) of some raspberry pis. Unfortunately, this cases the following error:

```
07:18:50.966 [main] ERROR c.c.c.c.CloudStoreClient - java.lang.RuntimeException: java.net.URISyntaxException: Expected scheme-specific part at index 5: file:
java.lang.RuntimeException: java.net.URISyntaxException: Expected scheme-specific part at index 5: file:
        at co.codewizards.cloudstore.core.util.UrlUtil.getFile(UrlUtil.java:65) ~[co.codewizards.cloudstore.core-0.10.3.jar:na]
        at co.codewizards.cloudstore.local.transport.FileRepoTransport.determineRemoteRootWithoutPathPrefix(FileRepoTransport.java:527) ~[co.codewizards.cloudstore.local-0.10.3.jar:na]
        at co.codewizards.cloudstore.core.repo.transport.AbstractRepoTransport.getRemoteRootWithoutPathPrefix(AbstractRepoTransport.java:73) ~[co.codewizards.cloudstore.core-0.10.3.jar:na]
        at co.codewizards.cloudstore.local.transport.FileRepoTransport.getLocalRepoManager(FileRepoTransport.java:516) ~[co.codewizards.cloudstore.local-0.10.3.jar:na]
        at co.codewizards.cloudstore.local.transport.FileRepoTransport.getClientRepositoryDto(FileRepoTransport.java:188) ~[co.codewizards.cloudstore.local-0.10.3.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:229) ~[co.codewizards.cloudstore.core-0.10.3.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.syncDown(RepoToRepoSync.java:178) ~[co.codewizards.cloudstore.core-0.10.3.jar:na]
        at co.codewizards.cloudstore.core.repo.sync.RepoToRepoSync.sync(RepoToRepoSync.java:141) ~[co.codewizards.cloudstore.core-0.10.3.jar:na]
        at co.codewizards.cloudstore.client.SyncSubCommand.sync(SyncSubCommand.java:119) ~[co.codewizards.cloudstore.client-0.10.3.jar:na]
        at co.codewizards.cloudstore.client.SyncSubCommand.run(SyncSubCommand.java:71) ~[co.codewizards.cloudstore.client-0.10.3.jar:na]
        at co.codewizards.cloudstore.client.CloudStoreClient.execute(CloudStoreClient.java:225) [co.codewizards.cloudstore.client-0.10.3.jar:na]
        at co.codewizards.cloudstore.client.CloudStoreClient.main(CloudStoreClient.java:157) [co.codewizards.cloudstore.client-0.10.3.jar:na]
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 5: file:
        at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_65]
        at java.net.URI$Parser.failExpecting(URI.java:2854) ~[na:1.8.0_65]
        at java.net.URI$Parser.parse(URI.java:3057) ~[na:1.8.0_65]
        at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_65]
        at java.net.URL.toURI(URL.java:939) ~[na:1.8.0_65]
        at co.codewizards.cloudstore.core.util.UrlUtil.getFile(UrlUtil.java:63) ~[co.codewizards.cloudstore.core-0.10.3.jar:na]
        ... 11 common frames omitted
```

**Comment by nlmarco** [comment]
Added test `co.codewizards.cloudstore.core.util.UrlUtilTest.rootFile()` and saw that the problem originates from `UrlUtil.canonicalizeURL(...)`, which converts "file:/" to "file:".

**Comment by nlmarco** [comment]
I changed `UrlUtil.canonicalizeURL(...)` to change the appended file part from "" to "/", if there is no host part. Thus, the URL "http://host.domain.tld/" is still canonicalized to "http://host.domain.tld" -- as it was before --, but the URL "file:/" is left unchanged (and not turned into "file:", anymore).
